name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  S3_BUCKET_NAME: auction-deploy    

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Java JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
